#!/usr/bin/env python3
"""Generate docs/assets/js/settings-data.js from the canonical tables in
docs/settings/index.md.

The reference page is the single source. Edit it, then run:

    contrib/gen-settings-data.py

and commit the regenerated file. Every table whose header is
"Setting | Values | Default | Notes" under a "## Panel" heading becomes
one explorer panel; the "Notes" cell is trimmed to its first sentence
(or two when the first is very short). Nothing else in the page is read.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REF = ROOT / "docs" / "settings" / "index.md"
OUT = ROOT / "docs" / "assets" / "js" / "settings-data.js"

HEADER = ["Setting", "Values", "Default", "Notes"]


def cells(line: str) -> list[str] | None:
    if not line.strip().startswith("|"):
        return None
    parts = line.strip().strip("|").split("|")
    return [c.strip() for c in parts]


def plain(text: str) -> str:
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    text = re.sub(r"\[(.*?)\]\((.*?)\)", r"\1", text)
    text = re.sub(r"`(.*?)`", r"\1", text)
    return text.strip()


def card_note(text: str) -> str:
    """The full reference note, minus cross-reference sentences: every
    card already links to the reference section, so 'See ...' carries
    nothing the card needs."""
    sentences = re.split(r"(?<=\.)\s+", text)
    kept = [s for s in sentences if not s.startswith("See ")]
    return " ".join(kept).strip()


def slug(heading: str) -> str:
    return heading.strip().lower().replace(" ", "-")


def main() -> None:
    lines = REF.read_text().splitlines()
    panels: list[dict] = []
    current: dict | None = None
    i = 0
    while i < len(lines):
        line = lines[i]
        heading = re.match(r"##\s+(.*)", line)
        if heading:
            current = {"panel": heading.group(1).strip(),
                       "anchor": slug(heading.group(1)), "items": []}
            i += 1
            continue
        row = cells(line)
        if row is not None and current is not None:
            # a table starts only when the header row matches exactly
            if row == HEADER:
                i += 2  # skip the separator row
                while i < len(lines):
                    cells_i = cells(lines[i])
                    if cells_i is None or len(cells_i) != 4:
                        break
                    name, values, default, note = (plain(c) for c in cells_i)
                    current["items"].append({
                        "name": name,
                        "values": values,
                        "def": default,
                        "note": card_note(note),
                    })
                    i += 1
                if current["items"]:
                    panels.append(current)
                current = None
                continue
        i += 1

    if len(panels) < 8:
        raise SystemExit(f"only {len(panels)} panels found — parser drift?")

    def dump(panels: list[dict]) -> str:
        out = ["window.ZP_SETTINGS = ["]
        for p in panels:
            out.append(f'  {{ "panel": {json.dumps(p["panel"], ensure_ascii=False)}, '
                       f'"anchor": {json.dumps(p["anchor"], ensure_ascii=False)}, "items": [')
            for it in p["items"]:
                out.append("    " + json.dumps(it, separators=(", ", ": "), ensure_ascii=False) + ",")
            out.append("  ] },")
        out.append("];")
        return "\n".join(out) + "\n"

    banner = (
        "/* Data for the settings explorer (docs/settings/explorer.md).\n"
        " *\n"
        " * GENERATED by contrib/gen-settings-data.py from the tables in\n"
        " * docs/settings/index.md — the reference page is canonical.\n"
        " * Edit that page, run the script, commit the result. Notes carry\n"
        " * the full reference wording minus 'See ...' sentences; the card\n"
        " * grid clamps long notes in CSS.\n"
        " */\n"
    )
    OUT.write_text(banner + dump(panels))
    total = sum(len(p["items"]) for p in panels)
    print(f"{len(panels)} panels, {total} settings -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
